api/urls.py
from django.urls import path

from api import views

app_name = "api"

urlpatterns = [
    
]

demo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('core/', include('core.urls')),
    path('', include('home.urls')),

]

home/urls.py
from django.urls import path

from home import views

app_name = "home"

urlpatterns = [
    path('',views.index.as_view(), name='index'),
    path('logout/',views.Logout.as_view(), name='logout'),
    path('signup/',views.Signup.as_view(), name='signup'),
]

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=32,
        widget=forms.TextInput(attrs={"type": "text", "class": "form-control"})
    )
    password = forms.CharField(
        max_length=32,
        widget=forms.PasswordInput(attrs={"type": "password","class": "form-control"})
    )


class UserForm(UserCreationForm):
    username = forms.CharField(
        max_length=32,
        widget=forms.TextInput(attrs={"type": "text", "class": "form-control"})
    )
    password1 = forms.CharField(
        max_length=32,
        widget=forms.PasswordInput(attrs={"type": "password", "class": "form-control"})
    )
    password2 = forms.CharField(
        max_length=32,
        widget=forms.PasswordInput(attrs={"type": "password", "class": "form-control"})
    )
    first_name = forms.CharField(
        max_length=32,
        widget=forms.TextInput(attrs={"type": "text", "class": "form-control"})
    )
    last_name = forms.CharField(
        max_length=32,
        widget=forms.TextInput(attrs={"type": "text", "class": "form-control"})
    )
    email = forms.EmailField(
        max_length=32,
        widget=forms.EmailInput(attrs={"type": "email", "class": "form-control"})
    )

home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

from django.urls import reverse_lazy

from django.views import generic

from home.forms import LoginForm, UserForm
# Create your views here.



class index(generic.View):
    template_name = 'home/index.html'
    context = {}
    form_class = LoginForm

    def get(self, request):
        self.context = {
            "users": User.objects.all(),
            "loginForm": self.form_class
        }
        return render(request, self.template_name, self.context)
    

    def post(self, request ):
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home:index')
        else:
            return redirect('home:index')


class Logout(generic.View):
    template_name = "home/index.html"
    context = {}

    def get(self, request):
        logout(request)
        return redirect("home:index")
    
class Signup(generic.CreateView):
    template_name = 'home/signup.html'
    model = User
    form_class = UserForm
    success_url = reverse_lazy('home:index')

    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(self.request, username=username, password=password)
        if user is not None:
            login(self.request, user)
            return redirect('home:index')
        else:
            return redirect("home:index")

templates/home/index.html
{% extends 'base/base.html' %}
{% block title %}INDEX VIEW{% endblock title%}
{% block content %}
    {% if request.user.is_authenticated %}
    <h1>Bienvenido User: {{ request.user.username }}</h1>
    <table class="table table-striped">
        <thead>
            <th>ID</th>
            <th>Username</th>
            <th>Email</th>
            <th></th>
            <th>Actions</th>
            <th></th>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.email }}</td>
                
                <td><a href="" class="btn btn-outline-info">Detail</a></td>
                <td><a href="" class="btn btn-outline-warning">Update</a></td>
                <td><a href="" class="btn btn-outline-danger">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <form action="" method="post">
            {% csrf_token %}
                {{ loginForm }}
                <button type="submit" class="btn btn-success">Login</button>
        </form>
        Si no tiene una cuenta: <a href="{% url 'home:signup' %}" class="btn btn-link">Click Aquí</a>
    

    {% endif %}
{% endblock content%}

templates/home/signup.html
{% extends "base/base.html" %}

{% block title %}SIGNUP VIEW{% endblock title %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    {{form}}
    <button type="submit" class="btn btn-success">SIGNUP</button>
    <a href="{% url 'home:index' %}">Cancel</a>
</form>

{% endblock content %}